### ISSUE TITLE
the bugs when i run the code 

### ISSUE THREAD

**Issue by JackLo111** [Evil0ctal/Fast-Powerful-Whisper-AI-Services-API#2]
Sorry, when i run the code as instuction. The following message is printed on the screen: Invalid argument(s) 'pool_size','max_overflow','pool_timeout' sent to create_engine(), using configuration SQLiteDialect_aiosqlite/NullPool/Engine. Please check that the keyword arguments are appropriate for this combination of components.

**Comment by Evil0ctal** [comment]
Hi can you provide me a full log with traceback?

**Comment by JackLo111** [comment]
Sure! The full log has been listed as follow. Moreover, I think I have encountered a slight problem that I can't use pip install pywin32==308.
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
INFO:     Started server process [1068213]
INFO:     Waiting for application startup.
2024-11-21 10:56:31,684 - app.database.DatabaseManager - ERROR - Unexpected error during database connection: Invalid argument(s) 'pool_size','max_overflow','pool_timeout' sent to create_engine(), using configuration SQLiteDialect_aiosqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
2024-11-21 10:56:31,686 - app.database.DatabaseManager - ERROR - Traceback (most recent call last):
  File "/data/jclu/lexu/Fast-Powerful-Whisper-AI-Services-API-main/app/database/DatabaseManager.py", line 103, in _connect
    self._engine = create_async_engine(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 697, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'pool_size','max_overflow','pool_timeout' sent to create_engine(), using configuration SQLiteDialect_aiosqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

ERROR:    Traceback (most recent call last):
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/lexu/Fast-Powerful-Whisper-AI-Services-API-main/app/main.py", line 92, in lifespan
    await db_manager.initialize()
  File "/data/jclu/lexu/Fast-Powerful-Whisper-AI-Services-API-main/app/database/DatabaseManager.py", line 92, in initialize
    await self._connect()
  File "/data/jclu/lexu/Fast-Powerful-Whisper-AI-Services-API-main/app/database/DatabaseManager.py", line 103, in _connect
    self._engine = create_async_engine(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 120, in create_async_engine
    sync_engine = _create_engine(url, **kw)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/data/jclu/anaconda3/envs/finance/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 697, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'pool_size','max_overflow','pool_timeout' sent to create_engine(), using configuration SQLiteDialect_aiosqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

ERROR:    Application startup failed. Exiting.

**Comment by Evil0ctal** [comment]
Hello, I’ve released a new version to address this issue! In my testing environment, I was using MySQL as the database, so I overlooked testing compatibility with SQLite. During the database engine initialization, some parameters specific to MySQL were inadvertently passed, which SQLite does not support, resulting in the project failing to start. Thank you so much for catching and reporting this issue!

**Comment by JackLo111** [comment]
Oh, I know what's problem with this. I have deployed it on my server with Linux. It seems that your code is intended to be deployed on windows. That explains why I can't finish it smoothly.

**Comment by JackLo111** [comment]
I think the project is a fantastic one! It's good to find so nice open-source project!

**Comment by Evil0ctal** [comment]
I’m glad you enjoyed this project! Yes, I did this in Windows, but it should work fine in Linux as well, though you may need to manually install the CUDA dependencies to use GPU accelerated inference, so feel free to ask me questions!
